apiVersion: v1
name: mxnet
version: 1.4.23
appVersion: 1.6.0
description: A flexible and efficient library for deep learning
keywords:
  - mxnet
  - python
  - machine
  - learning
home: https://mxnet.apache.org/
sources:
  - https://github.com/bitnami/bitnami-docker-mxnet
maintainers:
  - name: Bitnami
    email: containers@bitnami.com
engine: gotpl
icon: https://bitnami.com/assets/stacks/mxnet/img/mxnet-stack-110x117.png
annotations:
  category: MachineLearning
