{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "moodle.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.moodlePassword }}
  moodle-password: {{ default "" .Values.moodlePassword | b64enc | quote }}
  {{- else }}
  moodle-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  smtp-password: {{ default "" .Values.smtpPassword | b64enc | quote }}
{{- end }}
