apiVersion: v1
name: mariadb-galera
version: 4.3.3
appVersion: 10.5.5
description: MariaDB Galera is a multi-master database cluster solution for synchronous replication and high availability.
keywords:
  - mariadb
  - mysql
  - database
  - sql
  - prometheus
  - galera
  - percona
home: https://mariadb.org
icon: https://bitnami.com/assets/stacks/mariadb-galera/img/mariadb-galera-stack-220x234.png
sources:
  - https://github.com/bitnami/bitnami-docker-mariadb-galera
  - https://github.com/prometheus/mysqld_exporter
maintainers:
  - name: Bitnami
    email: containers@bitnami.com
engine: gotpl
annotations:
  category: Database
