apiVersion: v1
kind: Service
metadata:
  name: {{ include "logstash.fullname" . }}-headless
  labels: {{- include "logstash.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  {{- range $key, $value := .Values.service.ports }}
    - name: {{ $key }}
{{ toYaml $value | indent 6 }}
  {{- end }}
  selector: {{ include "logstash.matchLabels" . | nindent 4 }}
