apiVersion: v1
kind: Service
metadata:
  name: {{ template "spark.fullname" . }}-headless
  labels: {{- include "spark.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector: {{- include "spark.matchLabels" . | nindent 4 }}
