apiVersion: v1
kind: Secret
metadata:
  name: {{ template "magento.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "magento.fullname" . }}
    helm.sh/chart: {{ template "magento.chart" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
type: Opaque
data:
  magento-password: "{{ b64enc (include "magento.password" .) }}"
