{{- if not .Values.mariadb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ghost.externalDb.secret.name" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.externalDatabase.password }}
  mariadb-password: {{ .Values.externalDatabase.password | b64enc | quote }}
  {{- end }}
{{- end }}
