{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "nginx-ingress.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.serviceAccount.annotations }}
  annotations: {{- include "nginx-ingress.tplValue" (dict "value" .Values.serviceAccount.annotations "context" $) | nindent 4 }}
  {{- end }}
  labels: {{- include "nginx-ingress.labels" . | nindent 4 }}
{{- end -}}
