{{- if eq .Values.mode "distributed" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mxnet.fullname" . }}-worker
  labels: {{- include "mxnet.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  podManagementPolicy: {{ .Values.podManagementPolicy }}
  serviceName: {{ template "mxnet.fullname" . }}-headless
  selector:
    matchLabels: {{- include "mxnet.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  replicas: {{ .Values.workerCount }}
  template:
    metadata:
      labels: {{- include "mxnet.labels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
{{- include "mxnet.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.affinity }}
      affinity: {{- include "mxnet.tplValue" (dict "value" .Values.affinity "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- include "mxnet.tplValue" (dict "value" .Values.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- include "mxnet.tplValue" (dict "value" .Values.tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
      {{- end }}
      {{- if or .Values.cloneFilesFromGit.enabled (and .Values.volumePermissions.enabled .Values.persistence.enabled) .Values.initContainers }}
      initContainers:
        {{- if .Values.cloneFilesFromGit.enabled }}
        - name: git-clone-repository
          image: {{ include "git.image" . }}
          imagePullPolicy: {{ .Values.git.pullPolicy | quote }}
          command:
            - /bin/sh
            - -c
            - |
              git clone {{ .Values.cloneFilesFromGit.repository }} --branch {{ .Values.cloneFilesFromGit.revision }} /app
          volumeMounts:
            - name: git-cloned-files
              mountPath: /app
        {{- end }}
        {{- if and .Values.volumePermissions.enabled .Values.persistence.enabled }}
        - name: volume-permissions
          image: {{ template "mxnet.volumePermissions.image" . }}
          imagePullPolicy: {{ default "" .Values.volumePermissions.image.pullPolicy | quote }}
          command:
            - /bin/bash
            - -ec
            - |
              chown -R {{ .Values.securityContext.runAsUser }}:{{ .Values.securityContext.fsGroup }} {{ .Values.persistence.mountPath }}
          securityContext:
            runAsUser: 0
          {{- if .Values.volumePermissions.resources }}
          resources: {{- toYaml .Values.volumePermissions.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
        {{- end }}
        {{- if .Values.initContainers }}
        {{- include "mxnet.tplValue" ( dict "value" .Values.initContainers "context" $) | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
        - name: mxnet
          workingDir: {{ .Values.entrypoint.workDir }}
          image: {{ include "mxnet.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command:
            - bash
            - -c
            - |
              WORKER_RANK=${POD_NAME##*-}
              ((WORKER_RANK++))
              export WORKER_RANK
              {{- include "mxnet.entrypoint" . | nindent 14 }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DMLC_ROLE
              value: "worker"
            - name: DMLC_NUM_WORKER
              value: {{ .Values.workerCount | quote }}
            - name: DMLC_NUM_SERVER
              value: {{ .Values.serverCount | quote }}
            - name: DMLC_PS_ROOT_URI
              value: {{ include "mxnet.fullname" . }}-scheduler
            - name: DMLC_PS_ROOT_PORT
              value: {{ .Values.schedulerPort | quote }}
            {{- if .Values.commonExtraEnvVars }}
            {{- include "mxnet.parseEnvVars" .Values.commonExtraEnvVars | nindent 12 }}
            {{- end }}
            {{- if .Values.workerExtraEnvVars }}
            {{- include "mxnet.parseEnvVars" .Values.workerExtraVars | nindent 12 }}
            {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            exec:
              command:
                - python3
                - -c
                - import mxnet; print(mxnet.__version__)
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            exec:
              command:
                - python3
                - -c
                - import mxnet; print(mxnet.__version__)
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.configMap }}
            - name: ext-files
              mountPath: /app
            {{- else if .Files.Glob "files/*" }}
            - name: local-files
              mountPath: /app
            {{- else if .Values.cloneFilesFromGit.enabled }}
            - name: git-cloned-files
              mountPath: /app
            {{- end }}
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
            {{- if .Values.existingSecret }}
            - name: secret-data
              mountPath: /secrets
            {{- end }}
        {{- if .Values.sidecars }}
        {{- include "mxnet.tplValue" ( dict "value" .Values.sidecars "context" $) | nindent 8 }}
        {{- end }}
      volumes:
        {{- if .Values.existingSecret }}
        - name: secret-data
          secret:
            secretName: {{ .Values.existingSecret }}
        {{- end }}
        {{- if .Values.configMap }}
        - name: ext-files
          configMap:
            name: {{ .Values.configMap }}
        {{- else if .Files.Glob "files/*" }}
        - name: local-files
          configMap:
            name: {{ include "mxnet.fullname" . }}-files
        {{- else if .Values.cloneFilesFromGit.enabled }}
        - name: git-cloned-files
          emptyDir: {}
        {{- end }}
{{- if not .Values.persistence.enabled }}
        - name: data
          emptyDir: {}
{{- else }}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels: {{- include "mxnet.matchLabels" . | nindent 10 }}
        {{- if .Values.persistence.annotations }}
        annotations: {{- include "mxnet.tplValue" ( dict "value" .Values.persistence.annotations "context" $) | nindent 10 }}
        {{- end }}
      spec:
        accessModes: {{- toYaml .Values.persistence.accessModes | nindent 10 }}
        {{ include "mxnet.storageClass" . }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
{{- end }}
{{- end }}
