{{- if not .Values.mariadb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "externaldb"  }}
  labels: {{- include "phabricator.labels" . | nindent 4 }}
type: Opaque
data:
  mariadb-root-password: {{ .Values.externalDatabase.rootPassword | b64enc | quote }}
{{- end }}
