{{- if .Values.persistence.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "wildfly.fullname" . }}
  labels: {{- include "wildfly.labels" . | nindent 4 }}
  annotations:
    volume.alpha.kubernetes.io/storage-class: {{ ternary "default" (trimPrefix "storageClassName: " (include "wildfly.storageClass" .)) (empty (include "wildfly.storageClass" .)) }}
spec:
  accessModes:
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{ include "wildfly.storageClass" . }}
{{- end -}}
