{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "ghost.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
  {{- if .Values.ingress.annotations }}
  {{- include "common.tplvalues.render" ( dict "value" .Values.ingress.annotations "context" $) | nindent 4 }}
  {{- end }}
  {{- if .Values.ingress.certManager }}
    kubernetes.io/tls-acme: "true"
  {{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .name }}
      http:
        paths:
          - path: {{ default "/" .path }}
            backend:
              serviceName: {{ include "ghost.fullname" $ }}
              servicePort: http
  {{- end }}
  tls:
  {{- range .Values.ingress.hosts }}
    {{- if .tls }}
    - hosts:
    {{- if .tlsHosts }}
    {{- range $host := .tlsHosts }}
      - {{ $host }}
    {{- end }}
    {{- else }}
      - {{ .name }}
    {{- end }}
      secretName: {{ .tlsSecret }}
    {{- end }}
  {{- end }}
{{- end }}
