{{- if and (.Values.externalRabbitmq.enabled) (not .Values.rabbitmq.enabled) (not .Values.externalRabbitmq.existingPasswordSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" (include "scdf.fullname" .) "externalrabbitmq" }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
data:
  rabbitmq-password: {{ .Values.externalRabbitmq.password | b64enc | quote }}
{{- end }}
