{{- if .Files.Glob "files/*" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mxnet.fullname" . }}-files
  labels: {{- include "mxnet.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "files/*").AsConfig | indent 2 }}
{{- end }}
