{{- if eq .Values.mode "distributed" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mxnet.fullname" . }}-headless
  labels: {{- include "mxnet.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector: {{- include "mxnet.matchLabels" . | nindent 4 }}
{{- end }}
