{{- if .Values.ldap.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "airflow.ldap" . }}
  labels: {{- include "airflow.labels" . | nindent 4 }}
type: Opaque
data:
  bind-password: {{ .Values.ldap.bindpw | b64enc | quote }}
{{- end -}}
